

# This file was *autogenerated* from the file gen_test_vectors.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_17 = Integer(17); _sage_const_48 = Integer(48)
import argparse
import random
import os
load("AMNS_FIOS.sage")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = "Generate test FIOS test vectors.")
    parser.add_argument("-w", metavar = "WIDTH", type = int, default = _sage_const_256 ,
                        help = "Bit-width of the test vectors.")
    parser.add_argument("-n", metavar = "NUMBER", type = int, default = None,
                        help = "Number of test vectors.")
    parser.add_argument("-N", metavar = "COEFF", type = int, default = None,
                        help = "Number of coefficients.")
    parser.add_argument("-L", metavar = "LAMBDA", type = int, default = _sage_const_2 ,
                        help = "LAMBDA parameter.")
    parser.add_argument("--name", metavar = "FILE NAME", type = str, default = None,
                        help = "Name of test vector file. Default : sim_<WIDTH>")
                        
    args = parser.parse_args()

    WIDTH = args.w
    N = args.N
    LAMBDA = args.L

    if args.n is not None:
        test_vectors_nb = args.n
    else:
        test_vectors_nb = _sage_const_1 

    if args.name is not None:
        filename = args.name + ".txt"
    else:
        filename = "sim_" + str(WIDTH) + "_" + str(N) + "_" + str(LAMBDA) + ".txt"
        

    filename = os.path.abspath(os.path.dirname(__file__)) + "/TEST_VECTORS/TXT/" + filename
    
    with open(filename, "w") as test_file:

        for i in range(test_vectors_nb):                    
        
            valid = _sage_const_0 
            count = _sage_const_0 
            while (not(valid) and count < _sage_const_5 ) :
                
                p = random_prime(_sage_const_2 **WIDTH, False, _sage_const_2 **(WIDTH-_sage_const_1 ))
            
                try:
                    AMNS_inst = AMNS(p, N, LAMBDA = LAMBDA)
                    valid = _sage_const_1 
                except Exception as error:
                    valid = _sage_const_0 
                    print(error)
                    print(p)
                    print(N)
                    print(LAMBDA)
                count += _sage_const_1 
                    
            w = _sage_const_17 
            W = _sage_const_2 **w
                    
            a_int = random.randrange(_sage_const_2 **(WIDTH-_sage_const_1 ), p)
            b_int = random.randrange(_sage_const_2 **(WIDTH-_sage_const_1 ), p)
                    
            E = AMNS_inst.E
            gamma = AMNS_inst.GAMMA

            phi_log2 = AMNS_inst.phi_log2
            phi = _sage_const_2 **phi_log2

            s = (phi_log2-_sage_const_1 )//_sage_const_17 +_sage_const_1 

            M = AMNS_inst.M
            M_prime = AMNS_inst.M_P

            M_prime_0 = M_prime.map_coefficients(lambda t : t % W)

            A = PolyRing(AMNS_inst.conv_in(a_int))
            B = PolyRing(AMNS_inst.conv_in(b_int))

            A_comp2 = polcomp2(A, (s-_sage_const_1 )*w+_sage_const_48 )
            B_comp2 = polcomp2(B, (s-_sage_const_1 )*w+_sage_const_48 )
            M_comp2 = polcomp2(M, (s-_sage_const_1 )*w+_sage_const_48 )

            A_comp2_arr = [A_comp2.map_coefficients(lambda t : (t >> (i*w)) % W) for i in range(s-_sage_const_1 )]
            A_comp2_arr.append(A_comp2.map_coefficients(lambda t : (t >> ((s-_sage_const_1 )*w)) % (_sage_const_2 **_sage_const_48 )))

            B_comp2_arr = [B_comp2.map_coefficients(lambda t : (t >> (i*w)) % W) for i in range(s-_sage_const_1 )]
            B_comp2_arr.append(B_comp2.map_coefficients(lambda t : (t >> ((s-_sage_const_1 )*w)) % (_sage_const_2 **_sage_const_48 )))

            M_comp2_arr = [M_comp2.map_coefficients(lambda t : (t >> (i*w)) % W) for i in range(s-_sage_const_1 )]
            M_comp2_arr.append(M_comp2.map_coefficients(lambda t : (t >> ((s-_sage_const_1 )*w)) % (_sage_const_2 **_sage_const_48 )))

            res_arr = AMNS_FIOS(A_comp2_arr, B_comp2_arr, E, M_comp2_arr, M_prime_0)

            res = PolyRing(_sage_const_0 )
            for i in range(s):
                res = res + res_arr[i].map_coefficients(lambda t : t << (i*w))
            
            test_file.write(f'WIDTH\n{WIDTH}\n\nPHI_LOG2\n{phi_log2}\n\nsw\n{s*w}\n\nGAMMA\n{gamma}\n\np\n{p}\n\na_int\n{a_int}\n\nb_int\n{b_int}\n\n')

            test_file.write("M\n")
            for i in range(N):
                test_file.write(f'{hex(list(M_comp2.map_coefficients(lambda t : t % _sage_const_2 **(s*w)))[i])[_sage_const_2 :]}\n')
                
            test_file.write("\nM_prime_0\n")
            for i in range(N):
                test_file.write(f'{hex(list(M_prime_0)[i])[_sage_const_2 :]}\n')

            test_file.write("\nA\n")
            for i in range(N):
                test_file.write(f'{hex(list(A_comp2.map_coefficients(lambda t : t % _sage_const_2 **(s*w)))[i])[_sage_const_2 :]}\n')
            
            test_file.write("\nB\n")
            for i in range(N):
                test_file.write(f'{hex(list(B_comp2.map_coefficients(lambda t : t % _sage_const_2 **(s*w)))[i])[_sage_const_2 :]}\n')
                
            test_file.write("\nres\n")
            for i in range(N):
                test_file.write(f'{hex(list(res)[i])[_sage_const_2 :]}\n')
                
            test_file.write("\n\n")
            
            print(poldecomp2(res, s*w)(gamma)*_sage_const_2 **(s*w) % p)
            print(a_int*b_int % p)

